name: front-production

# This action works with pull requests and pushes
on:
  release:
    types:
      - released

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-east1
  SERVICE_NAME: hubr-front-production

jobs:
  setup-build-push-deploy:
    name: Setup, Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName

      - name: Announce version
        run: echo "creating library for ${GIT_TAG_NAME}"

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "296.0.1"
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker

      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" --build-arg ENVIRONMENT=production --build-arg VERSION=${GIT_TAG_NAME} --build-arg API_URL=${{ secrets.API_URL }} --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} --build-arg REDIRECT_URI=${{ secrets.REDIRECT_URI }} .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --memory "521Mi" \
            --allow-unauthenticated

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "*Deploy on prod*"
          mention: "here"
          mention_if: "failure"
          channel: "#random"
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
